name: Deploy Backend to Hugging Face Spaces

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # Replace these with your actual Hugging Face details in your workflow
          HF_USERNAME: ashutoshkumar46
          HF_SPACE_NAME: leettrack-backend
        run: |
          cd backend
          git init
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b main
          git add .
          git commit -m "Deploying commit ${{ github.sha }} to Hugging Face Spaces"
          git remote add hf https://huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME
          git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main
